# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

sphinx-documentation-html:
  tags:
    - docker, debian
  image:
    name: ${CI_REGISTRY}/internal/docker-sphinx:latest
  script:
    - make html
  artifacts:
    paths:
      - _build/html

deployment_staging:
  when: manual
  tags:
    - docker, debian
  needs:
    - sphinx-documentation-html
  image:
    name: ${CI_REGISTRY}/internal/docker-utils:latest
  script:
    - lftp -e "mirror --reverse --delete -n -e _build/html /igor-pro-coding-conventions; bye" -u $FTP_USER_DOCS_STAGING,$FTP_PW_DOCS_STAGING byte-physics.de

deployment:
  tags:
    - docker, debian
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  needs:
    - sphinx-documentation-html
  image:
    name: ${CI_REGISTRY}/internal/docker-utils:latest
  script:
    - lftp -e "mirror --reverse --delete -n -e _build/html /igor-pro-coding-conventions; bye" -u $FTP_USER_DOCS,$FTP_PW_DOCS byte-physics.de
