# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

test:
  tags:
    - debian, docker
  image:
    name: ${CI_REGISTRY}/internal/docker-utils:latest
  variables:
    DOCKER_AUTH_CONFIG: "${DOCKER_AUTH_CONFIG_UTILS}"
  script:
    - echo "Hello universe"
